name: "Buf Generate"
description: "Set up Buf and generate code from proto"
runs:
  using: "composite"
  steps:
    - name: Set up Buf
      uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1

    - name: Generate code from proto
      shell: bash
      run: |
        mkdir -p src/proto
        buf generate
