// @generated
// This file is @generated by prost-build.
#[expect(clippy::derive_partial_eq_without_eq, reason = "generated code: prost::Message does not implement Eq")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCookiesRequest {
    #[prost(string, tag="1")]
    pub host: ::prost::alloc::string::String,
}
#[expect(clippy::derive_partial_eq_without_eq, reason = "generated code: prost::Message does not implement Eq")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCookiesResponse {
    #[prost(string, tag="1")]
    pub cookies: ::prost::alloc::string::String,
}
include!("cookiejar.v1.tonic.rs");
// @@protoc_insertion_point(module)